/**
 * Iris Event System - Auto-generated C Implementation
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated: 2025-10-12T05:33:14.592Z
 * Schema version: 1.0
 */

#include <iris/iris_events.h>
#include <core/string.h>

/* Protocol Constants */
#define IRIS_MAGIC_BYTE_1 0x49  /* 'I' */
#define IRIS_MAGIC_BYTE_2 0x52  /* 'R' */

/* Global State */
static iris_transport_write_fn g_transport_fn = NULL;

void iris_events_init(iris_transport_write_fn transport_fn) {
    g_transport_fn = transport_fn;
}

/* Weak timestamp function - user should override */
__attribute__((weak)) uint64_t iris_get_timestamp_us(void) {
    return 0;  /* Override this in your kernel */
}

void iris_send_event_raw(uint16_t event_id, const void* payload, uint16_t payload_len) {
    if (!g_transport_fn) return;
    
    /* Build packet header (14 bytes) */
    uint8_t header[14];
    uint16_t offset = 0;
    
    /* Magic bytes */
    header[offset++] = IRIS_MAGIC_BYTE_1;
    header[offset++] = IRIS_MAGIC_BYTE_2;
    
    /* Event ID (little-endian) */
    header[offset++] = event_id & 0xFF;
    header[offset++] = (event_id >> 8) & 0xFF;
    
    /* Timestamp (little-endian) */
    uint64_t timestamp = iris_get_timestamp_us();
    for (int i = 0; i < 8; i++) {
        header[offset++] = (timestamp >> (i * 8)) & 0xFF;
    }
    
    /* Payload length (little-endian) */
    header[offset++] = payload_len & 0xFF;
    header[offset++] = (payload_len >> 8) & 0xFF;
    
    /* Send header */
    g_transport_fn(header, 14);
    
    /* Send payload */
    if (payload_len > 0) {
        g_transport_fn((const uint8_t*)payload, payload_len);
    }
}

void iris_send_system_init(uint8_t cpu_id, uint32_t boot_flags) {
    iris_event_system_init_t event;
    event.cpu_id = cpu_id;
    event.boot_flags = boot_flags;
    
    iris_send_event_raw(0x0001, &event, sizeof(event));
}

void iris_send_heap_alloc(uint64_t address, uint64_t size, uint8_t cpu_id) {
    iris_event_heap_alloc_t event;
    event.address = address;
    event.size = size;
    event.cpu_id = cpu_id;
    
    iris_send_event_raw(0x0100, &event, sizeof(event));
}

void iris_send_heap_free(uint64_t address, uint64_t size, uint8_t cpu_id) {
    iris_event_heap_free_t event;
    event.address = address;
    event.size = size;
    event.cpu_id = cpu_id;
    
    iris_send_event_raw(0x0101, &event, sizeof(event));
}

void iris_send_physical_page_alloc(uint64_t physical_address, uint32_t page_count, uint8_t cpu_id) {
    iris_event_physical_page_alloc_t event;
    event.physical_address = physical_address;
    event.page_count = page_count;
    event.cpu_id = cpu_id;
    
    iris_send_event_raw(0x0102, &event, sizeof(event));
}

void iris_send_physical_page_free(uint64_t physical_address, uint32_t page_count, uint8_t cpu_id) {
    iris_event_physical_page_free_t event;
    event.physical_address = physical_address;
    event.page_count = page_count;
    event.cpu_id = cpu_id;
    
    iris_send_event_raw(0x0103, &event, sizeof(event));
}

void iris_send_virtual_page_alloc(uint64_t virtual_address, uint64_t physical_address, uint32_t page_count, uint64_t flags, uint8_t cpu_id) {
    iris_event_virtual_page_alloc_t event;
    event.virtual_address = virtual_address;
    event.physical_address = physical_address;
    event.page_count = page_count;
    event.flags = flags;
    event.cpu_id = cpu_id;
    
    iris_send_event_raw(0x0104, &event, sizeof(event));
}

void iris_send_virtual_page_unmap(uint64_t virtual_address, uint32_t page_count, uint8_t cpu_id) {
    iris_event_virtual_page_unmap_t event;
    event.virtual_address = virtual_address;
    event.page_count = page_count;
    event.cpu_id = cpu_id;
    
    iris_send_event_raw(0x0105, &event, sizeof(event));
}

void iris_send_syscall_entry(uint64_t syscall_num, int64_t pid, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5, uint64_t arg6, uint8_t cpu_id) {
    iris_event_syscall_entry_t event;
    event.syscall_num = syscall_num;
    event.pid = pid;
    event.arg1 = arg1;
    event.arg2 = arg2;
    event.arg3 = arg3;
    event.arg4 = arg4;
    event.arg5 = arg5;
    event.arg6 = arg6;
    event.cpu_id = cpu_id;
    
    iris_send_event_raw(0x0200, &event, sizeof(event));
}
