/**
 * Iris Event System - Auto-generated C Header
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated: 2025-10-12T05:33:14.591Z
 * Schema version: 1.0
 */

#ifndef IRIS_EVENTS_H
#define IRIS_EVENTS_H

#include <types.h>
#include <core/string.h>

/* Event IDs */
#define IRIS_EVENT_SYSTEM_INIT    0x0001
#define IRIS_EVENT_HEAP_ALLOC    0x0100
#define IRIS_EVENT_HEAP_FREE    0x0101
#define IRIS_EVENT_PHYSICAL_PAGE_ALLOC    0x0102
#define IRIS_EVENT_PHYSICAL_PAGE_FREE    0x0103
#define IRIS_EVENT_VIRTUAL_PAGE_ALLOC    0x0104
#define IRIS_EVENT_VIRTUAL_PAGE_UNMAP    0x0105
#define IRIS_EVENT_SYSCALL_ENTRY    0x0200

/* Event Categories */
typedef enum {
    IRIS_CATEGORY_SYSTEM = 0,
    IRIS_CATEGORY_MEMORY = 1,
    IRIS_CATEGORY_INTERRUPT = 2,
} iris_event_category_t;

/* Event Data Structures */
/**
 * Kernel boot initialization
 * Event ID: 0x0001
 */
typedef struct __attribute__((packed)) {
    uint8_t cpu_id;  /* CPU core that booted */
    uint32_t boot_flags;  /* Boot configuration flags */
} iris_event_system_init_t;

/**
 * Kernel heap memory allocation (malloc/zmalloc)
 * Event ID: 0x0100
 */
typedef struct __attribute__((packed)) {
    uint64_t address;  /* Allocated memory address */
    uint64_t size;  /* Size of allocation in bytes */
    uint8_t cpu_id;  /* CPU core that performed allocation */
} iris_event_heap_alloc_t;

/**
 * Kernel heap memory deallocation (free)
 * Event ID: 0x0101
 */
typedef struct __attribute__((packed)) {
    uint64_t address;  /* Freed memory address */
    uint64_t size;  /* Size of freed block in bytes */
    uint8_t cpu_id;  /* CPU core that performed free */
} iris_event_heap_free_t;

/**
 * Physical page allocation
 * Event ID: 0x0102
 */
typedef struct __attribute__((packed)) {
    uint64_t physical_address;  /* Physical address of allocated page(s) */
    uint32_t page_count;  /* Number of contiguous pages allocated */
    uint8_t cpu_id;  /* CPU core that allocated pages */
} iris_event_physical_page_alloc_t;

/**
 * Physical page deallocation
 * Event ID: 0x0103
 */
typedef struct __attribute__((packed)) {
    uint64_t physical_address;  /* Physical address of freed page(s) */
    uint32_t page_count;  /* Number of contiguous pages freed */
    uint8_t cpu_id;  /* CPU core that freed pages */
} iris_event_physical_page_free_t;

/**
 * Virtual page mapping
 * Event ID: 0x0104
 */
typedef struct __attribute__((packed)) {
    uint64_t virtual_address;  /* Virtual address of allocated page(s) */
    uint64_t physical_address;  /* Physical address mapped to virtual page */
    uint32_t page_count;  /* Number of pages allocated */
    uint64_t flags;  /* Page table flags (permissions, etc) */
    uint8_t cpu_id;  /* CPU core that performed allocation */
} iris_event_virtual_page_alloc_t;

/**
 * Virtual page unmapping
 * Event ID: 0x0105
 */
typedef struct __attribute__((packed)) {
    uint64_t virtual_address;  /* Virtual address being unmapped */
    uint32_t page_count;  /* Number of pages unmapped */
    uint8_t cpu_id;  /* CPU core that performed unmap */
} iris_event_virtual_page_unmap_t;

/**
 * System call entry into kernel
 * Event ID: 0x0200
 */
typedef struct __attribute__((packed)) {
    uint64_t syscall_num;  /* System call number (0-1023) */
    int64_t pid;  /* Process ID making the syscall */
    uint64_t arg1;  /* First syscall argument (rdi) */
    uint64_t arg2;  /* Second syscall argument (rsi) */
    uint64_t arg3;  /* Third syscall argument (rdx) */
    uint64_t arg4;  /* Fourth syscall argument (r8) */
    uint64_t arg5;  /* Fifth syscall argument (r9) */
    uint64_t arg6;  /* Sixth syscall argument (r10) */
    uint8_t cpu_id;  /* CPU core handling the syscall */
} iris_event_syscall_entry_t;

/* Transport abstraction */
typedef void (*iris_transport_write_fn)(const uint8_t* data, uint16_t len);

/* Core Functions */

/**
 * Initialize the Iris event system
 * @param transport_fn Function to call for writing event data
 */
void iris_events_init(iris_transport_write_fn transport_fn);

/**
 * Get current timestamp in microseconds
 * User must implement this function
 */
uint64_t iris_get_timestamp_us(void);

/**
 * Send a raw event with custom payload
 * @param event_id Event ID
 * @param payload Pointer to payload data
 * @param payload_len Length of payload
 */
void iris_send_event_raw(uint16_t event_id, const void* payload, uint16_t payload_len);

/* High-level Event Functions */
/**
 * Send SYSTEM_INIT event
 * Kernel boot initialization
 * @param cpu_id CPU core that booted
 * @param boot_flags Boot configuration flags
 */
void iris_send_system_init(uint8_t cpu_id, uint32_t boot_flags);

/**
 * Send HEAP_ALLOC event
 * Kernel heap memory allocation (malloc/zmalloc)
 * @param address Allocated memory address
 * @param size Size of allocation in bytes
 * @param cpu_id CPU core that performed allocation
 */
void iris_send_heap_alloc(uint64_t address, uint64_t size, uint8_t cpu_id);

/**
 * Send HEAP_FREE event
 * Kernel heap memory deallocation (free)
 * @param address Freed memory address
 * @param size Size of freed block in bytes
 * @param cpu_id CPU core that performed free
 */
void iris_send_heap_free(uint64_t address, uint64_t size, uint8_t cpu_id);

/**
 * Send PHYSICAL_PAGE_ALLOC event
 * Physical page allocation
 * @param physical_address Physical address of allocated page(s)
 * @param page_count Number of contiguous pages allocated
 * @param cpu_id CPU core that allocated pages
 */
void iris_send_physical_page_alloc(uint64_t physical_address, uint32_t page_count, uint8_t cpu_id);

/**
 * Send PHYSICAL_PAGE_FREE event
 * Physical page deallocation
 * @param physical_address Physical address of freed page(s)
 * @param page_count Number of contiguous pages freed
 * @param cpu_id CPU core that freed pages
 */
void iris_send_physical_page_free(uint64_t physical_address, uint32_t page_count, uint8_t cpu_id);

/**
 * Send VIRTUAL_PAGE_ALLOC event
 * Virtual page mapping
 * @param virtual_address Virtual address of allocated page(s)
 * @param physical_address Physical address mapped to virtual page
 * @param page_count Number of pages allocated
 * @param flags Page table flags (permissions, etc)
 * @param cpu_id CPU core that performed allocation
 */
void iris_send_virtual_page_alloc(uint64_t virtual_address, uint64_t physical_address, uint32_t page_count, uint64_t flags, uint8_t cpu_id);

/**
 * Send VIRTUAL_PAGE_UNMAP event
 * Virtual page unmapping
 * @param virtual_address Virtual address being unmapped
 * @param page_count Number of pages unmapped
 * @param cpu_id CPU core that performed unmap
 */
void iris_send_virtual_page_unmap(uint64_t virtual_address, uint32_t page_count, uint8_t cpu_id);

/**
 * Send SYSCALL_ENTRY event
 * System call entry into kernel
 * @param syscall_num System call number (0-1023)
 * @param pid Process ID making the syscall
 * @param arg1 First syscall argument (rdi)
 * @param arg2 Second syscall argument (rsi)
 * @param arg3 Third syscall argument (rdx)
 * @param arg4 Fourth syscall argument (r8)
 * @param arg5 Fifth syscall argument (r9)
 * @param arg6 Sixth syscall argument (r10)
 * @param cpu_id CPU core handling the syscall
 */
void iris_send_syscall_entry(uint64_t syscall_num, int64_t pid, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5, uint64_t arg6, uint8_t cpu_id);


#endif /* IRIS_EVENTS_H */