/*
 * Stellux-specific config.h for Dropbear.
 * Normally generated by autoconf, but hand-crafted for Stellux cross-compilation.
 */

#ifndef DROPBEAR_CONFIG_H_
#define DROPBEAR_CONFIG_H_

/* Standard integer types */
#define HAVE_UINT8_T 1
#define HAVE_UINT16_T 1
#define HAVE_UINT32_T 1
#define HAVE_U_INT8_T 0
#define HAVE_U_INT16_T 0
#define HAVE_U_INT32_T 0
#define HAVE_INTTYPES_H 1

/* System headers available in musl */
#define HAVE_NETINET_IN_H 1
#define HAVE_NETINET_TCP_H 1
#define HAVE_NETDB_H 1
#define HAVE_SYS_UIO_H 1
#define HAVE_PATHS_H 1
#define HAVE_UTMP_H 1
#define HAVE_SYS_RANDOM_H 1

/* Headers NOT available */
/* #undef HAVE_CRYPT_H */
/* #undef HAVE_SHADOW_H */
/* #undef HAVE_LIBUTIL_H */
/* #undef HAVE_UTIL_H */
/* #undef HAVE_PTY_H */
/* #undef HAVE_STROPTS_H */
/* #undef HAVE_LASTLOG_H */
/* #undef HAVE_UTMPX_H */
#define HAVE_LIBGEN_H 1
/* #undef HAVE_MACH_MACH_TIME_H */
/* #undef HAVE_SYS_PRCTL_H */
/* #undef HAVE_LINUX_PKT_SCHED_H */

/* Functions available in musl */
#define HAVE_CRYPT 1
#define HAVE_GETRANDOM 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_WRITEV 1
#define HAVE_BASENAME 1
#define HAVE_FCHMOD 1
#define HAVE_EXPLICIT_BZERO 1

/* Struct members available in musl */
#define HAVE_STRUCT_ADDRINFO 1
#define HAVE_GETADDRINFO 1
#define HAVE_FREEADDRINFO 1
#define HAVE_GAI_STRERROR 1
#define HAVE_STRUCT_SOCKADDR_STORAGE 1
#define HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY 1
#define HAVE_STRUCT_STAT_ST_BLKSIZE 1

/* Functions available in musl but not previously enabled */
#define HAVE_GETNAMEINFO 1

/* Functions NOT available on Stellux (yet) */
/* #undef HAVE_FORK */
/* #undef HAVE_DAEMON */
/* #undef HAVE_OPENPTY */
/* #undef HAVE_FEXECVE */
/* #undef HAVE_CLEARENV */
/* #undef HAVE_GETUSERSHELL */
/* #undef HAVE_GETGROUPLIST */
/* #undef HAVE_STRLCPY */
/* #undef HAVE_STRLCAT */
/* #undef HAVE_MEMSET_S */

/* No IPv6 on Stellux at the network stack level, but musl headers
 * define the structs. Tell Dropbear they exist so fake-rfc2553.h
 * doesn't redefine them. */
#define HAVE_STRUCT_IN6_ADDR 1
#define HAVE_STRUCT_SOCKADDR_IN6 1

/* No utmp/wtmp/lastlog on Stellux */
/* #undef HAVE_SETUTENT */
/* #undef HAVE_ENDUTENT */
/* #undef HAVE_PUTUTLINE */
/* #undef HAVE_SETUTXENT */
/* #undef HAVE_ENDUTXENT */
/* #undef HAVE_PUTUTXLINE */
/* #undef HAVE_LOGIN */
/* #undef HAVE_LOGOUT */
/* #undef HAVE_LOGWTMP */

/* No PAM */
/* #undef HAVE_LIBPAM */

/* No devpts - Stellux uses its own PTY mechanism */
/* #undef HAVE_DEV_PTMX */

/* Dropbear feature defines */
#define LOCALOPTIONS_H_EXISTS 1
#define BUNDLED_LIBTOM 1

/* Sizeof types for libtommath */
#define SIZEOF_UNSIGNED_LONG 8
#define SIZEOF_UNSIGNED_LONG_LONG 8

#endif /* DROPBEAR_CONFIG_H_ */
