# Stellux Display Manager Configuration

[desktop]
bg_color=0xFF2D2D30

[theme]
bar_color=0xFF1E1E1E
bar_font_size=14
accent_color=0xFF888888

[taskbar:terminal]
label=Terminal
path=/initrd/bin/stlxterm

[taskbar:doom]
label=DOOM
path=/initrd/bin/doom
