[desktop]
bg_color=0xFF2D2D30

[theme]
bar_color=0xFF1E1E1E
bar_font_size=14
accent_color=0xFF888888
text_color=0xFFCCCCCC

[taskbar]
height=48
icon_size=32
spacing=8

[shortcut:new_terminal]
key=ctrl+alt+t
action=exec
path=/initrd/bin/stlxterm

[taskbar:terminal]
label=Terminal
path=/initrd/bin/stlxterm

[taskbar:doom]
label=DOOM
path=/initrd/bin/doom

[autostart:terminal]
path=/initrd/bin/stlxterm
