#ifndef STLXDM_DECOR_H
#define STLXDM_DECOR_H

#define STLXDM_DECOR_TITLEBAR_H    28
#define STLXDM_DECOR_BORDER_W      1
#define STLXDM_DECOR_TITLE_FONT    13
#define STLXDM_DECOR_TITLE_COLOR   0xFFBBBBBB
#define STLXDM_DECOR_TITLEBAR_BG   0xFF252530
#define STLXDM_DECOR_TITLEBAR_FOCUSED_BG 0xFF2A2A3A
#define STLXDM_DECOR_BORDER_COLOR  0xFF3A3A4A
#define STLXDM_DECOR_BORDER_FOCUSED 0xFF5A5A7A
#define STLXDM_DECOR_SEPARATOR     0xFF444455

#endif /* STLXDM_DECOR_H */
