[taskbar:browser]
label=Browser
path=/usr/bin/content_shell
args=--no-sandbox --no-zygote --disable-gpu --in-process-gpu --content-shell-host-window-size=760x480 https://example.com
icon=/etc/res/icons/icon_browser_32x32.bmp
