[taskbar:browser]
label=Browser
path=/usr/bin/chrome
args=--no-sandbox --no-zygote --disable-gpu --in-process-gpu --user-data-dir=/tmp/chrome --no-first-run --password-store=basic --renderer-process-limit=2 --window-size=780,540 --lang=en-US --accept-lang=en-US https://example.com
icon=/etc/res/icons/icon_browser_32x32.bmp
