#ifndef STELLUX_SYSCALL_HANDLERS_SYS_TASK_H
#define STELLUX_SYSCALL_HANDLERS_SYS_TASK_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(getpid);
DECLARE_SYSCALL(getuid);
DECLARE_SYSCALL(geteuid);
DECLARE_SYSCALL(getgid);
DECLARE_SYSCALL(getegid);
DECLARE_SYSCALL(exit);
DECLARE_SYSCALL(exit_group);
DECLARE_SYSCALL(set_tid_address);
DECLARE_SYSCALL(nanosleep);
DECLARE_SYSCALL(sysinfo);
DECLARE_SYSCALL(sched_getaffinity);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_TASK_H
