#ifndef STELLUX_SYSCALL_HANDLERS_SYS_PIPE_H
#define STELLUX_SYSCALL_HANDLERS_SYS_PIPE_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(pipe);
DECLARE_SYSCALL(pipe2);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_PIPE_H
