#ifndef STELLUX_SYSCALL_HANDLERS_SYS_FD_H
#define STELLUX_SYSCALL_HANDLERS_SYS_FD_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(openat);
DECLARE_SYSCALL(open);
DECLARE_SYSCALL(read);
DECLARE_SYSCALL(write);
DECLARE_SYSCALL(close);
DECLARE_SYSCALL(stat);
DECLARE_SYSCALL(fstat);
DECLARE_SYSCALL(newfstatat);
DECLARE_SYSCALL(getdents64);
DECLARE_SYSCALL(fcntl);
DECLARE_SYSCALL(unlinkat);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_FD_H
