#ifndef STELLUX_SYSCALL_HANDLERS_SYS_SYSINFO_H
#define STELLUX_SYSCALL_HANDLERS_SYS_SYSINFO_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(sysinfo);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_SYSINFO_H
