#ifndef STELLUX_SYSCALL_HANDLERS_SYS_DUP_H
#define STELLUX_SYSCALL_HANDLERS_SYS_DUP_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(dup);
DECLARE_SYSCALL(dup2);
DECLARE_SYSCALL(dup3);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_DUP_H
