#ifndef STELLUX_SYSCALL_HANDLERS_SYS_SELECT_H
#define STELLUX_SYSCALL_HANDLERS_SYS_SELECT_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(select);
DECLARE_SYSCALL(pselect6);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_SELECT_H
