#ifndef STELLUX_SYSCALL_HANDLERS_SYS_SHUTDOWN_H
#define STELLUX_SYSCALL_HANDLERS_SYS_SHUTDOWN_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(shutdown);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_SHUTDOWN_H
