#ifndef STELLUX_SYSCALL_HANDLERS_SYS_MISC_H
#define STELLUX_SYSCALL_HANDLERS_SYS_MISC_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(access);
DECLARE_SYSCALL(uname);
DECLARE_SYSCALL(rename);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_MISC_H
