#ifndef STELLUX_SYSCALL_HANDLERS_SYS_PRLIMIT_H
#define STELLUX_SYSCALL_HANDLERS_SYS_PRLIMIT_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(prlimit64);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_PRLIMIT_H
