#ifndef STELLUX_SYSCALL_HANDLERS_SYS_ELEVATE_H
#define STELLUX_SYSCALL_HANDLERS_SYS_ELEVATE_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(elevate);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_ELEVATE_H
