#ifndef STELLUX_SYSCALL_HANDLERS_SYS_FD_H
#define STELLUX_SYSCALL_HANDLERS_SYS_FD_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(openat);
DECLARE_SYSCALL(open);
DECLARE_SYSCALL(lseek);
DECLARE_SYSCALL(read);
DECLARE_SYSCALL(write);
DECLARE_SYSCALL(close);
DECLARE_SYSCALL(stat);
DECLARE_SYSCALL(fstat);
DECLARE_SYSCALL(newfstatat);
DECLARE_SYSCALL(getdents64);
DECLARE_SYSCALL(fcntl);
DECLARE_SYSCALL(unlinkat);
DECLARE_SYSCALL(unlink);
DECLARE_SYSCALL(rmdir);
DECLARE_SYSCALL(getcwd);
DECLARE_SYSCALL(chdir);
DECLARE_SYSCALL(fchdir);
DECLARE_SYSCALL(mkdirat);
DECLARE_SYSCALL(mkdir);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_FD_H
