#ifndef STELLUX_SYSCALL_HANDLERS_SYS_IO_H
#define STELLUX_SYSCALL_HANDLERS_SYS_IO_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(readv);
DECLARE_SYSCALL(writev);
DECLARE_SYSCALL(ioctl);
DECLARE_SYSCALL(pread64);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_IO_H
