#ifndef STELLUX_SYSCALL_HANDLERS_SYS_EVENTFD_H
#define STELLUX_SYSCALL_HANDLERS_SYS_EVENTFD_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(eventfd2);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_EVENTFD_H
