#ifndef STELLUX_SYSCALL_HANDLERS_SYS_NET_H
#define STELLUX_SYSCALL_HANDLERS_SYS_NET_H

#include "syscall/syscall_table.h"

DECLARE_SYSCALL(socket);
DECLARE_SYSCALL(bind);
DECLARE_SYSCALL(listen);
DECLARE_SYSCALL(accept);
DECLARE_SYSCALL(connect);
DECLARE_SYSCALL(sendto);
DECLARE_SYSCALL(recvfrom);

#endif // STELLUX_SYSCALL_HANDLERS_SYS_NET_H
