#ifndef STLX_SYSCALL_NUMS_H
#define STLX_SYSCALL_NUMS_H

#define SYS_PROC_CREATE  1010
#define SYS_PROC_START   1011
#define SYS_PROC_WAIT    1012
#define SYS_PROC_DETACH  1013
#define SYS_PROC_INFO    1014

#endif /* STLX_SYSCALL_NUMS_H */
