#!/usr/bin/env python3
"""Writes qt.mk for a built kit: what a program using it compiles and links with.

That is measured on the recipe's probe programs: the compile and link flags Qt's
CMake gives probe_public over probe_plain, and the private include directories
probe_private gets on top. The link flags carry each static plugin's init object,
which imports the plugin into the program.

Usage: qtmk.py <probe build dir> <kit prefix> <qt version> <arch> <output dir>
"""
import pathlib
import shlex
import subprocess
import sys

# Flags whose value is the next argument, kept together as one flag
PAIRED_FLAGS = {"-isystem", "-I", "-include", "-iquote", "-idirafter", "-o", "-MT", "-MF", "-c", "-x"}

# Arguments naming the file a command compiles, which say nothing about the kit
FILE_FLAGS = {"-o", "-MT", "-MF", "-c", "-MD", "-MMD"}

# The program picks its own language standard, any one from Qt's minimum up
STANDARD_FLAG = "-std="

PLUGIN_INIT_SUFFIX = "_init.cpp.o"


def ninja_commands(build, target):
    result = subprocess.run(["ninja", "-C", build, "-t", "commands", target],
                            check=True, capture_output=True, text=True)
    return [line for line in result.stdout.splitlines() if line.strip()]


def flags_of(command):
    """The arguments after the compiler, each paired flag with its value as one item."""
    args = shlex.split(command.removeprefix(": && ").removesuffix(" && :"))[1:]
    flags = []
    i = 0
    while i < len(args):
        if args[i] in PAIRED_FLAGS and i + 1 < len(args):
            flags.append(f"{args[i]} {args[i + 1]}")
            i += 2
        else:
            flags.append(args[i])
            i += 1

    return flags


def compile_flags(build, target, source):
    for command in ninja_commands(build, target):
        if " -c " in command and command.rstrip().endswith(source):
            return [flag for flag in flags_of(command)
                    if flag.split(" ")[0] not in FILE_FLAGS and not flag.startswith(STANDARD_FLAG)]

    sys.exit(f"qtmk: no compile command of {source} for {target}")


def link_flags(build, target):
    return [flag for flag in flags_of(ninja_commands(build, target)[-1]) if not flag.startswith("-o ")]


def added(flags, base):
    present = set(base)
    return [flag for flag in flags if flag not in present]


def make_variable(name, items):
    if not items:
        return f"{name} :=\n"

    return f"{name} := \\\n" + " \\\n".join(f"\t{item}" for item in items) + "\n"


def main():
    build, prefix, version, arch, out = sys.argv[1:]
    prefix = prefix.rstrip("/")

    def in_kit(flag):
        return flag.replace(prefix, "$(QT_DIR)")

    plain = compile_flags(build, "probe_plain", "plain.cpp")
    public = compile_flags(build, "probe_public", "widgets.cpp")
    private = compile_flags(build, "probe_private", "widgets.cpp")
    cppflags = [in_kit(flag) for flag in added(public, plain)]
    private_cppflags = [in_kit(flag) for flag in added(private, public)]

    # The probe's own objects are relative paths, everything else Qt adds is the kit's
    linked = added(link_flags(build, "probe_public"), link_flags(build, "probe_plain"))
    ldlibs = [in_kit(flag) for flag in linked if flag.startswith(("-", prefix))]

    for flag in cppflags + private_cppflags + ldlibs:
        if "/" in flag and "$(QT_DIR)" not in flag:
            sys.exit(f"qtmk: {flag} names a path outside the kit")

    if not any(flag.endswith(PLUGIN_INIT_SUFFIX) and "/plugins/" in flag for flag in ldlibs):
        sys.exit("qtmk: probe_public links no static plugin's init object")

    pathlib.Path(out, "qt.mk").write_text(
        f"# Generated by the qt recipe: what a program using QtWidgets and QtSvg from\n"
        f"# this kit compiles and links with. The includer sets QT_DIR to the kit's directory.\n"
        f"QT_VERSION := {version}\n"
        f"QT_ARCH := {arch}\n"
        + make_variable("QT_CPPFLAGS", cppflags)
        + make_variable("QT_PRIVATE_CPPFLAGS", private_cppflags)
        + make_variable("QT_LDLIBS", ldlibs))


if __name__ == "__main__":
    main()
